# Generated by Django 5.1.11 on 2025-07-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
