# Generated by Django 5.1.11 on 2025-07-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image_couverture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_couverture',
        ),
    ]
